# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "13.4.2" # this should be changed

package:
  name: "mojo-rustls-ffi"
  version: 0.1.0

source:
  # - path: ./librustls.dylib
  - path: ../LICENSE

build:
  script:
    - mkdir -p ${PREFIX}/share/mojo-rustls-ffi
    - git clone --depth=1 git@github.com:rustls/rustls-ffi.git
    - cd rustls-ffi && cargo cinstall --library-type=cdylib --destdir=${PREFIX}/share/mojo-rustls-ffi/librustls.dylib
    - cd .. && rm -R rustls-ffi

about:
  homepage: https://github.com/rustls/mojo-rustls-ffi
  license: MIT
  license_file: LICENSE
  summary: Rustls FFI bindings - use Rustls from any language
  repository: https://github.com/rustls/mojo-rustls-ffi